<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.0" />
    <PackageReference Include="ClosedXML" Version="0.102.2" />
    <PackageReference Include="System.IO.Ports" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RFID_API_ver1">
      <HintPath>libs\RFID_API_ver1.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
